package Design;
import Structure.cm2100part3startingpoint.*;
//import java.awt.KeyboardFocusManager;
import java.util.*;
import java.awt.*;
import javax.swing.*;
import java.io.File;
/**
 *
 * @author ashayapi
 */
public class StartScreen extends javax.swing.JFrame {
    private User user;
    //private PlayList myMedia;
    //private PlayList playing;

    /**
     * Creates new form StartScreen
     */
    //public StartScreen(User user, PlayList myMedia, PlayList playing) {
    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        userNameTextField = new javax.swing.JTextField();
        validateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        loginIconLabel = new javax.swing.JLabel();
        goBackLabel = new javax.swing.JLabel();
        startPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        registerTextField = new javax.swing.JTextField();
        registerUserButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        registerIconLabel = new javax.swing.JLabel();
        goBackRegisterLabel = new javax.swing.JLabel();
        successfullRegistrationPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        proceedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Media PlayList System");
        setBackground(new java.awt.Color(161, 214, 226));
        setResizable(false);

        loginPanel.setVisible(false);
        loginPanel.setBackground(new java.awt.Color(161, 214, 226));
        loginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginPanel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        loginPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        loginPanel.setMinimumSize(new java.awt.Dimension(356, 578));

        userNameTextField.setBackground(new java.awt.Color(241, 241, 242));
        userNameTextField.setFont(new java.awt.Font("Shree Devanagari 714", 2, 18)); // NOI18N
        userNameTextField.setForeground(new java.awt.Color(25, 149, 173));
        userNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userNameTextField.setText("username");
        userNameTextField.setToolTipText("Enter your username here");
        userNameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        userNameTextField.setCaretColor(new java.awt.Color(188, 186, 190));
        userNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userNameTextField.setMaximumSize(new java.awt.Dimension(250, 38));
        userNameTextField.setMinimumSize(new java.awt.Dimension(250, 38));
        userNameTextField.setName(""); // NOI18N
        userNameTextField.setSelectedTextColor(new java.awt.Color(188, 186, 190));
        userNameTextField.setSelectionEnd(0);
        userNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userNameTextFieldMousePressed(evt);
            }
        });
        userNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameTextFieldKeyTyped(evt);
            }
        });

        validateButton.setBackground(new java.awt.Color(161, 214, 226));
        validateButton.setFont(new java.awt.Font("Shree Devanagari 714", 0, 27)); // NOI18N
        validateButton.setForeground(new java.awt.Color(241, 241, 242));
        validateButton.setText("Validate User");
        validateButton.setToolTipText("Validate username");
        validateButton.setActionCommand("Validate");
        validateButton.setAlignmentY(0.0F);
        validateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 241, 242), 1, true));
        validateButton.setContentAreaFilled(false);
        validateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        validateButton.setName(""); // NOI18N
        validateButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                validateButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                validateButtonFocusLost(evt);
            }
        });
        validateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                validateButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                validateButtonMouseEntered(evt);
            }
        });
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 241, 242));
        jLabel1.setText("Don't have an account?");
        jLabel1.setToolTipText("Press here to register");

        registerLabel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 19)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(241, 241, 242));
        registerLabel.setText("Register");
        registerLabel.setToolTipText("Click here to register");
        registerLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerLabelFocusLost(evt);
            }
        });
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerLabelMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerLabelMouseEntered(evt);
            }
        });

        loginIconLabel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 48)); // NOI18N
        loginIconLabel.setForeground(new java.awt.Color(241, 241, 242));
        loginIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login-icon.png"))); // NOI18N
        loginIconLabel.setText("User Name:");
        loginIconLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        loginIconLabel.setFocusTraversalKeysEnabled(false);
        loginIconLabel.setFocusable(false);
        loginIconLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginIconLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        goBackLabel.setBackground(new java.awt.Color(161, 214, 226));
        goBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-overcast.png"))); // NOI18N
        goBackLabel.setToolTipText("Go back");
        goBackLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                goBackLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                goBackLabelFocusLost(evt);
            }
        });
        goBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goBackLabelMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(loginIconLabel)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerLabel)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(goBackLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(loginIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 48, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addComponent(goBackLabel)
                .addGap(28, 28, 28))
        );

        userNameTextField.getAccessibleContext().setAccessibleName("userNameTextField");
        validateButton.getAccessibleContext().setAccessibleName("validateButton");
        validateButton.getAccessibleContext().setAccessibleDescription("");
        loginIconLabel.getAccessibleContext().setAccessibleName("loginLabel");
        goBackLabel.getAccessibleContext().setAccessibleName("goBackLabel");

        startPanel.setBackground(new java.awt.Color(161, 214, 226));
        startPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        startPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        startPanel.setPreferredSize(new java.awt.Dimension(395, 590));

        loginButton.setBackground(new java.awt.Color(161, 214, 226));
        loginButton.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        loginButton.setForeground(new java.awt.Color(241, 241, 242));
        loginButton.setText("Log in");
        loginButton.setToolTipText("Click to Log in");
        loginButton.setAlignmentX(0.5F);
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 241, 242), 2, true));
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setFocusable(false);
        loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginButton.setName(""); // NOI18N
        loginButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedLoginButton(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostLoginButton(evt);
            }
        });
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitedLoginButton(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredLoginButton(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(161, 214, 226));
        registerButton.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        registerButton.setForeground(new java.awt.Color(241, 241, 242));
        registerButton.setText("Register");
        registerButton.setToolTipText("Click to register");
        registerButton.setAlignmentX(0.5F);
        registerButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 241, 242), 2, true));
        registerButton.setBorderPainted(false);
        registerButton.setContentAreaFilled(false);
        registerButton.setFocusable(false);
        registerButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedRegisterButton(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostRegisterButton(evt);
            }
        });
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitedRegisterButton(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredRegisterButton(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        loginButton.getAccessibleContext().setAccessibleName("loginButton");
        loginButton.getAccessibleContext().setAccessibleDescription("");
        registerButton.getAccessibleContext().setAccessibleName("registerButton");

        registerPanel.setVisible(false);
        registerPanel.setBackground(new java.awt.Color(161, 214, 226));
        registerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerPanel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        registerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        registerPanel.setMinimumSize(new java.awt.Dimension(383, 578));
        registerPanel.setPreferredSize(new java.awt.Dimension(395, 590));

        registerTextField.setBackground(new java.awt.Color(241, 241, 242));
        registerTextField.setFont(new java.awt.Font("Shree Devanagari 714", 2, 18)); // NOI18N
        registerTextField.setForeground(new java.awt.Color(25, 149, 173));
        registerTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        registerTextField.setText("username");
        registerTextField.setToolTipText("Enter your username here");
        registerTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        registerTextField.setCaretColor(new java.awt.Color(188, 186, 190));
        registerTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        registerTextField.setMaximumSize(new java.awt.Dimension(250, 38));
        registerTextField.setMinimumSize(new java.awt.Dimension(250, 38));
        registerTextField.setName(""); // NOI18N
        registerTextField.setSelectedTextColor(new java.awt.Color(188, 186, 190));
        registerTextField.setSelectionEnd(0);
        registerTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerTextFieldMousePressed(evt);
            }
        });
        registerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registerTextFieldKeyTyped(evt);
            }
        });

        registerUserButton.setBackground(new java.awt.Color(161, 214, 226));
        registerUserButton.setFont(new java.awt.Font("Shree Devanagari 714", 0, 27)); // NOI18N
        registerUserButton.setForeground(new java.awt.Color(241, 241, 242));
        registerUserButton.setText("Register User");
        registerUserButton.setToolTipText("Click here to register");
        registerUserButton.setActionCommand("Validate");
        registerUserButton.setAlignmentY(0.0F);
        registerUserButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 241, 242), 1, true));
        registerUserButton.setContentAreaFilled(false);
        registerUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerUserButton.setName(""); // NOI18N
        registerUserButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerUserButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerUserButtonFocusLost(evt);
            }
        });
        registerUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerUserButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerUserButtonMouseEntered(evt);
            }
        });
        registerUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 241, 242));
        jLabel2.setText("Already have an account?");
        jLabel2.setToolTipText("Press here to log in");

        loginLabel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 19)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(241, 241, 242));
        loginLabel.setText("Log in");
        loginLabel.setToolTipText("Click here to log in");
        loginLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginLabelFocusLost(evt);
            }
        });
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginLabelMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLabelMouseEntered(evt);
            }
        });

        registerIconLabel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 48)); // NOI18N
        registerIconLabel.setForeground(new java.awt.Color(241, 241, 242));
        registerIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/register-icon.png"))); // NOI18N
        registerIconLabel.setText("Enter your name:");
        registerIconLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        registerIconLabel.setFocusTraversalKeysEnabled(false);
        registerIconLabel.setFocusable(false);
        registerIconLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerIconLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        goBackRegisterLabel.setBackground(new java.awt.Color(161, 214, 226));
        goBackRegisterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-overcast.png"))); // NOI18N
        goBackRegisterLabel.setToolTipText("Go back");
        goBackRegisterLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                goBackRegisterLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                goBackRegisterLabelFocusLost(evt);
            }
        });
        goBackRegisterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goBackRegisterLabelMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackRegisterLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackRegisterLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(registerIconLabel)
                    .addComponent(registerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginLabel)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(goBackRegisterLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(registerIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 49, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addComponent(goBackRegisterLabel)
                .addGap(28, 28, 28))
        );

        registerUserButton.getAccessibleContext().setAccessibleName("registerUserButton");
        loginLabel.getAccessibleContext().setAccessibleName("loginLabel");
        goBackRegisterLabel.getAccessibleContext().setAccessibleName("goBackRegisterLabel");

        successfullRegistrationPanel.setVisible(false);
        successfullRegistrationPanel.setBackground(new java.awt.Color(161, 214, 226));
        successfullRegistrationPanel.setToolTipText("");
        successfullRegistrationPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        successfullRegistrationPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        successfullRegistrationPanel.setPreferredSize(new java.awt.Dimension(395, 590));

        jLabel4.setFont(new java.awt.Font("Shree Devanagari 714", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 241, 242));
        jLabel4.setText("WELCOME");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Shree Devanagari 714", 0, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 241, 242));
        jLabel5.setText("<html>You can now explore all the great features</htmla");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        usernameLabel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 48)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(241, 241, 242));
        usernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Shree Devanagari 714", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 241, 242));
        jLabel6.setText("MEDIA PLAYLIST");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Shree Devanagari 714", 0, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(241, 241, 242));
        jLabel7.setText("of");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        proceedButton.setBackground(new java.awt.Color(161, 214, 226));
        proceedButton.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        proceedButton.setForeground(new java.awt.Color(241, 241, 242));
        proceedButton.setText("Proceed");
        proceedButton.setToolTipText("Click to proceed");
        proceedButton.setAlignmentX(0.5F);
        proceedButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 241, 242), 2, true));
        proceedButton.setBorderPainted(false);
        proceedButton.setContentAreaFilled(false);
        proceedButton.setFocusable(false);
        proceedButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        proceedButton.setName(""); // NOI18N
        proceedButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                proceedButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                proceedButtonFocusLost(evt);
            }
        });
        proceedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proceedButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proceedButtonButtonMouseEntered(evt);
            }
        });
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout successfullRegistrationPanelLayout = new javax.swing.GroupLayout(successfullRegistrationPanel);
        successfullRegistrationPanel.setLayout(successfullRegistrationPanelLayout);
        successfullRegistrationPanelLayout.setHorizontalGroup(
            successfullRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successfullRegistrationPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(successfullRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(usernameLabel)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(proceedButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, successfullRegistrationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        successfullRegistrationPanelLayout.setVerticalGroup(
            successfullRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successfullRegistrationPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(successfullRegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(successfullRegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginPanel.getAccessibleContext().setAccessibleName("");
        loginPanel.setVisible(false);
        registerPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTextFieldKeyTyped
        // TODO add your handling code here:
        userNameTextField.setFont(new java.awt.Font("Shree Devanagari 714", 1, 19));
    }//GEN-LAST:event_userNameTextFieldKeyTyped

    private void validateButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_validateButtonFocusGained
        // TODO add your handling code here:
        validateButton.setBorderPainted(true);
    }//GEN-LAST:event_validateButtonFocusGained

    private void validateButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_validateButtonFocusLost
        // TODO add your handling code here:
        validateButton.setBorderPainted(false);
    }//GEN-LAST:event_validateButtonFocusLost

    private void validateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validateButtonMouseExited
        // TODO add your handling code here:
        validateButton.setBorderPainted(false);
    }//GEN-LAST:event_validateButtonMouseExited

    private void validateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validateButtonMouseEntered
        // TODO add your handling code here:
        validateButton.setBorderPainted(true);
    }//GEN-LAST:event_validateButtonMouseEntered

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        // TODO add your handling code here:
        //System.out.println(userNameTextField.getText());
        if(User.checkDatabase(userNameTextField.getText())) {
            user = User.logIn(userNameTextField.getText());
            //myMedia = new PlayList(user);
            //playing = new PlayList(user);
            MainScreen ms = new MainScreen(user);
            ms.setVisible(true);
            this.setVisible(false);
            //System.out.println(user.toString());
        }
        else {
            JOptionPane.showMessageDialog(null, "Oops! We cant't seem to find this name in our database! Why don't you try to register?", "User not found" ,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_validateButtonActionPerformed

    private void userNameTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameTextFieldMousePressed
        // TODO add your handling code here:
        userNameTextField.setText(null);
    }//GEN-LAST:event_userNameTextFieldMousePressed

    private void registerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseEntered
        // TODO add your handling code here:
        registerLabel.setForeground(new java.awt.Color(25,149,173));
    }//GEN-LAST:event_registerLabelMouseEntered

    private void registerLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerLabelFocusGained
        // TODO add your handling code here:
        registerLabel.setForeground(new java.awt.Color(25,149,173));
    }//GEN-LAST:event_registerLabelFocusGained

    private void registerLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerLabelFocusLost
        // TODO add your handling code here:
        registerLabel.setForeground(new java.awt.Color(241,241,242));
    }//GEN-LAST:event_registerLabelFocusLost

    private void registerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseExited
        // TODO add your handling code here:
        registerLabel.setForeground(new java.awt.Color(241,241,242));
    }//GEN-LAST:event_registerLabelMouseExited

    private void goBackLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseEntered
        // TODO add your handling code here:
        goBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-glacier-blue.png"))); 
    }//GEN-LAST:event_goBackLabelMouseEntered

    private void goBackLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseExited
        // TODO add your handling code here:
        goBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-overcast.png")));
    }//GEN-LAST:event_goBackLabelMouseExited

    private void goBackLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goBackLabelFocusGained
        // TODO add your handling code here:
        goBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-glacier-blue.png"))); 
    }//GEN-LAST:event_goBackLabelFocusGained

    private void goBackLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goBackLabelFocusLost
        // TODO add your handling code here:
        goBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-overcast.png")));
    }//GEN-LAST:event_goBackLabelFocusLost

    private void goBackLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMousePressed
        // TODO add your handling code here:
        loginPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_goBackLabelMousePressed

    private void registerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMousePressed
        // TODO add your handling code here:
        loginPanel.setVisible(false);
        registerPanel.setVisible(true);
        registerTextField.setFont(new java.awt.Font("Shree Devanagari 714", 2, 18));
        registerTextField.setText("username");
    }//GEN-LAST:event_registerLabelMousePressed

    private void registerTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerTextFieldMousePressed
        // TODO add your handling code here:
        registerTextField.setText(null);
    }//GEN-LAST:event_registerTextFieldMousePressed

    private void registerTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerTextFieldKeyTyped
        // TODO add your handling code here:
        registerTextField.setFont(new java.awt.Font("Shree Devanagari 714", 1, 19));
    }//GEN-LAST:event_registerTextFieldKeyTyped

    private void registerUserButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerUserButtonFocusGained
        // TODO add your handling code here:
        registerUserButton.setBorderPainted(true);
    }//GEN-LAST:event_registerUserButtonFocusGained

    private void registerUserButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerUserButtonFocusLost
        // TODO add your handling code here:
        registerUserButton.setBorderPainted(false);
    }//GEN-LAST:event_registerUserButtonFocusLost

    private void registerUserButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserButtonMouseExited
        // TODO add your handling code here:
        registerUserButton.setBorderPainted(false);
    }//GEN-LAST:event_registerUserButtonMouseExited

    private void registerUserButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserButtonMouseEntered
        // TODO add your handling code here:
        registerUserButton.setBorderPainted(true);
    }//GEN-LAST:event_registerUserButtonMouseEntered

    private void registerUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserButtonActionPerformed
        // TODO add your handling code here:
        if(User.checkDatabase(registerTextField.getText())) {
            JOptionPane.showMessageDialog(null, "Oops! We seem to already have a user with this name on our database! Why don't you try to log in?", "User already exists" ,JOptionPane.ERROR_MESSAGE);
        }
        else {
            User.registerUser(registerTextField.getText());
            user = new User(registerTextField.getText(), 1000);
            File mediaFile = new File("/Users/ashayapi/Desktop/MediaPlayList/src/Database/" + user.getUsername() + ".txt");
            File currentFile = new File("/Users/ashayapi/Desktop/MediaPlayList/src/Database/" + user.getUsername() + "-playing.txt");
            //myMedia = new PlayList(user);
            //playing = new PlayList(user);
            registerPanel.setVisible(false);
            usernameLabel.setText(user.getUsername());
            successfullRegistrationPanel.setVisible(true);
        }
    }//GEN-LAST:event_registerUserButtonActionPerformed

    private void loginLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginLabelFocusGained
        // TODO add your handling code here:
        loginLabel.setForeground(new java.awt.Color(25,149,173));
    }//GEN-LAST:event_loginLabelFocusGained

    private void loginLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginLabelFocusLost
        // TODO add your handling code here:
        loginLabel.setForeground(new java.awt.Color(241,241,242));
    }//GEN-LAST:event_loginLabelFocusLost

    private void loginLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMousePressed
        // TODO add your handling code here:
        registerPanel.setVisible(false);
        loginPanel.setVisible(true);
        userNameTextField.setFont(new java.awt.Font("Shree Devanagari 714", 2, 18));
        userNameTextField.setText("username");
    }//GEN-LAST:event_loginLabelMousePressed

    private void loginLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseExited
        // TODO add your handling code here:
        loginLabel.setForeground(new java.awt.Color(241,241,242));
    }//GEN-LAST:event_loginLabelMouseExited

    private void loginLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseEntered
        // TODO add your handling code here:
        loginLabel.setForeground(new java.awt.Color(25,149,173));
    }//GEN-LAST:event_loginLabelMouseEntered

    private void goBackRegisterLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goBackRegisterLabelFocusGained
        // TODO add your handling code here:
        goBackRegisterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-glacier-blue.png"))); 
    }//GEN-LAST:event_goBackRegisterLabelFocusGained

    private void goBackRegisterLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goBackRegisterLabelFocusLost
        // TODO add your handling code here:
        goBackRegisterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-overcast.png")));
    }//GEN-LAST:event_goBackRegisterLabelFocusLost

    private void goBackRegisterLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackRegisterLabelMousePressed
        // TODO add your handling code here:
        registerPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_goBackRegisterLabelMousePressed

    private void goBackRegisterLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackRegisterLabelMouseExited
        // TODO add your handling code here:
        goBackRegisterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-overcast.png"))); 
    }//GEN-LAST:event_goBackRegisterLabelMouseExited

    private void goBackRegisterLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackRegisterLabelMouseEntered
        // TODO add your handling code here:
        goBackRegisterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-arrow-glacier-blue.png"))); 
    }//GEN-LAST:event_goBackRegisterLabelMouseEntered

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        startPanel.setVisible(false);
        registerPanel.setVisible(true);
        registerTextField.setFont(new java.awt.Font("Shree Devanagari 714", 2, 18));
        registerTextField.setText("username");
    }//GEN-LAST:event_registerButtonActionPerformed

    private void mouseEnteredRegisterButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredRegisterButton
        // TODO add your handling code here:
        registerButton.setBorderPainted(true);
        loginButton.setFocusable(true);
        registerButton.setFocusable(true);
    }//GEN-LAST:event_mouseEnteredRegisterButton

    private void mouseExitedRegisterButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitedRegisterButton
        // TODO add your handling code here:
        registerButton.setBorderPainted(false);
    }//GEN-LAST:event_mouseExitedRegisterButton

    private void focusLostRegisterButton(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostRegisterButton
        // TODO add your handling code here:
        registerButton.setBorderPainted(false);
    }//GEN-LAST:event_focusLostRegisterButton

    private void focusGainedRegisterButton(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedRegisterButton
        // TODO add your handling code here:
        registerButton.setBorderPainted(true);
    }//GEN-LAST:event_focusGainedRegisterButton

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        startPanel.setVisible(false);
        loginPanel.setVisible(true);
        userNameTextField.setFont(new java.awt.Font("Shree Devanagari 714", 2, 18));
        userNameTextField.setText("username");

    }//GEN-LAST:event_loginButtonActionPerformed

    private void mouseEnteredLoginButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredLoginButton
        // TODO add your handling code here:
        loginButton.setBorderPainted(true);
        loginButton.setFocusable(true);
        registerButton.setFocusable(true);
    }//GEN-LAST:event_mouseEnteredLoginButton

    private void mouseExitedLoginButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitedLoginButton
        // TODO add your handling code here:
        loginButton.setBorderPainted(false);
    }//GEN-LAST:event_mouseExitedLoginButton

    private void focusLostLoginButton(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostLoginButton
        // TODO add your handling code here:
        loginButton.setBorderPainted(false);
    }//GEN-LAST:event_focusLostLoginButton

    private void focusGainedLoginButton(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedLoginButton
        // TODO add your handling code here:
        loginButton.setBorderPainted(true);
    }//GEN-LAST:event_focusGainedLoginButton

    private void proceedButtonButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedButtonButtonMouseEntered
        // TODO add your handling code here:
        proceedButton.setBorderPainted(true);
    }//GEN-LAST:event_proceedButtonButtonMouseEntered

    private void proceedButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedButtonMouseExited
        // TODO add your handling code here:
        proceedButton.setBorderPainted(false);
    }//GEN-LAST:event_proceedButtonMouseExited

    private void proceedButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proceedButtonFocusGained
        // TODO add your handling code here:
        proceedButton.setBorderPainted(true);
    }//GEN-LAST:event_proceedButtonFocusGained

    private void proceedButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proceedButtonFocusLost
        // TODO add your handling code here:
        proceedButton.setBorderPainted(false);
    }//GEN-LAST:event_proceedButtonFocusLost

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        // TODO add your handling code here:
        MainScreen ms = new MainScreen(user);
        ms.setVisible(true);
        this.dispose();
        //this.setVisible(false);
        /*AddStudentDialog asd = new AddStudentDialog(this, true, this.students);
        asd.setVisible(true);
        String str = "All Students\n";
        for (Student s: this.students){
            str += s.toString() + "\n";
        }
        this.jTextArea1.setText(str);*/
    }//GEN-LAST:event_proceedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JLabel goBackRegisterLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginIconLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton proceedButton;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerIconLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JTextField registerTextField;
    private javax.swing.JButton registerUserButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JPanel successfullRegistrationPanel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables
}
